### ISSUE TITLE
miniverse/map/installations-json API endpoint throwing 500 errors

### ISSUE THREAD

**Issue by pdurbin** [IQSS/miniverse#62] opened 2017-08-04 13:05 UTC
Unfortunately, not much after I posted on how to list of Dataverse installations as JSON at https://groups.google.com/d/msg/dataverse-community/HceZ-0h3-ys/z706eXxICQAJ I started getting 500 errors at https://services.dataverse.harvard.edu/miniverse/map/installations-json

We should fix the 500 error and in my opinion we should change the wording of the error message to better set expectations. Here's how it looks right now:

![screen shot 2017-08-04 at 9 02 20 am](https://user-images.githubusercontent.com/21006/28969771-fcc6f294-78f3-11e7-912b-eacb8f204d44.png)

**Comment by jggautier** [comment] 2017-08-29 19:34
It's working now.

I think the error happens when entered installations are set to "Inactive" or are missing certain fields (maybe latitude and longitude?).

**Comment by pdurbin** [comment] 2017-08-30 13:51
@jggautier thanks! What do you think? Should we keep this issue open to fix the code to be more forgiving about the data? Or should we close it?

**Comment by jggautier** [comment] 2017-08-30 15:33
I've been slowly testing which data might be breaking that json URL, slowly because when I make changes to the database (add or edit an installation), it takes a while for those changes to be reflected in the json.

I'd like to at least know which fields are mandatory for the json URL to work.

**Comment by jggautier** [comment] 2017-08-30 16:29
@pdurbin and I spoke. We know that the problem is related to something with the data (or lack of data) in the installations fields (lat/long, name, "full name" etc.). It'll be easier to make sure that anyone entering a new installation enters data in all of those fields. I'll open a ticket for this and close this one.

**Closed by jggautier** 2017-08-30 16:29 UTC
